// <auto-generated />
namespace PseudoCell.MyDataContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addGameName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addGameName));
        
        string IMigrationMetadata.Id
        {
            get { return "201710230225062_addGameName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
