// <auto-generated />
namespace PseudoCell.MyDataContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dec9b : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dec9b));
        
        string IMigrationMetadata.Id
        {
            get { return "201712092215512_dec9b"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
